### ISSUE TITLE
Why library loaded uses file mappings for name

### ISSUE THREAD

**Issue by stevemk14ebr** [x64dbg/TitanEngine#2]
I'd like to spend some time to improve the library loader in x64dbg, to call exports and such like olly allows. When i was browsing the source i noticed that the dll name is communicated by a 'weird' usage of file mappings between titan engine and the loader exe. It creates a file mapping in titan engine side https://github.com/x64dbg/TitanEngine/blob/7976be4edd84e923f24b8e68fc710262a6f3f4b0/TitanEngine/TitanEngine.Debugger.cpp#L505  and writes dll name, then opens this mapping on the loader side https://github.com/x64dbg/TitanEngine/blob/7976be4edd84e923f24b8e68fc710262a6f3f4b0/TitanEngineLoaders/LibraryLoader/LibraryLoader.cpp#L13. Why not just pass the arguments via command line?

Additionally since i will be spending time on a new loader, are there any specific desires about how this should be implemented or features to be added?

**Comment by mrexodia** [comment]
The reason was related to escaping iirc. I’m not sure a loader like ollydbg makes sense, but feel free to try. I recommend doing it separately from x64dbg and TitanEngine at first though. In my experience it’s much easier to write 10 lines of C to call whatever you want with whatever parameters you want.

**Comment by stevemk14ebr** [comment]
I agree it's not hard to write a little stub exe and debug that, but even just adding the ability to call exports would be nice. This is common question I see at classes and from beginners. 

Agree on the separate bit, if I just had the loader pop up a gui of its own would that be acceptable? 

NOTE (edit): to compile i had to change to vs2013 xp toolset (from just vs2013) & then disable SAFESEH for the aplib.dll to link properly. Idk if this is typical but it works.

**Comment by mrexodia** [comment]
I think this got solved because x64dbg now uses `loaddll.exe`, which you can customize. The TitanEngine DLL debugging functionality isn't used anymore...
